### ISSUE TITLE
Stack smashing detected - Error 

### ISSUE THREAD

**Issue by MikeWLloyd** [BoevaLab/FREEC#92]
I am trying to run control-freec via singularity (image ` control-freec_11.6--h1b792b2_1.sif`) on a sample with the following config file: 

```
[general]
BedGraphOutput = TRUE
chrFiles = /fastscratch/lloydm/8d7a192defa08d02b633f305e10578/Chromosomes
chrLenFile = /fastscratch/lloydm/8d7a192defa08d02b633f305e10578/GRCm38.len
forceGCcontentNormalization = 1
maxThreads = 1
minimalSubclonePresence = 100
ploidy = 2
sex = XX
readCountThreshold = 10
breakPointThreshold = 0.8
breakPointType = 2

coefficientOfVariation = 0.05
gemMappabilityFile = /fastscratch/lloydm/8d7a192defa08d02b633f305e10578/GRCm38_68_mm10.gem

[sample]
inputFormat = pileup
mateFile = /fastscratch/lloydm/8d7a192defa08d02b633f305e10578/846_KB1P_T.pileup
mateOrientation = FR

[BAF]
SNPfile = /fastscratch/lloydm/8d7a192defa08d02b633f305e10578/mgp.v5.merged.snps_all.dbSNP142.vcf.gz

[target]
```

However, I am getting the following error when trying to run the tool: 

```
$ singularity run control-freec_11.6--h1b792b2_1.sif freec -conf 846_KB1P_T.config.txt
Control-FREEC v11.6 : a method for automatic detection of copy number alterations, subclones and for accurate estimation of contamination and main ploidy using deep-sequencing data
Multi-threading mode using 8 threads
..consider the sample being female
..Breakpoint threshold for segmentation of copy number profiles is 0.8
..telocenromeric set to 50000
..FREEC is not going to adjust profiles for a possible contamination by normal cells
..Coefficient Of Variation set equal to 0.05
..it will be used to evaluate window size
..Output directory:	.
..Directory with files containing chromosome sequences:	/fastscratch/lloydm/8d7a192defa08d02b633f305e10578/Chromosomes
..Sample file:	/fastscratch/lloydm/8d7a192defa08d02b633f305e10578/846_KB1P_T.pileup
..Sample input format:	pileup
..minimal expected GC-content (general parameter "minExpectedGC") was set to 0.35
..maximal expected GC-content (general parameter "maxExpectedGC") was set to 0.55
..Polynomial degree for "ReadCount ~ GC-content" normalization is 3 or 4: will try both
..Minimal CNA length (in windows) is 1
..File with chromosome lengths:	/fastscratch/lloydm/8d7a192defa08d02b633f305e10578/GRCm38.len
..Using the default minimal mappability value of 0.85
..uniqueMatch = FALSE
..average ploidy set to 2
..break-point type set to 2
..noisyData set to 0
..Control-FREEC will not look for subclones
..will use SNP positions from /fastscratch/lloydm/8d7a192defa08d02b633f305e10578/mgp.v5.merged.snps_all.dbSNP142.vcf.gz to calculate BAF profiles
..Starting reading /fastscratch/lloydm/8d7a192defa08d02b633f305e10578/mgp.v5.merged.snps_all.dbSNP142.vcf.gz to get SNP positions
*** stack smashing detected ***: <unknown> terminated
SIGABRT: abort
PC=0x473c4b m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x1b849, 0x6, 0x0, 0xc000173ef0, 0x49de52, 0x1b849)
	/usr/lib64/go-1.11.1/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc000173eb8 sp=0xc000173eb0 pc=0x473c4b
syscall.Kill(0x1b849, 0x6, 0x4388ee, 0xc000173f20)
	/usr/lib64/go-1.11.1/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc000173f00 sp=0xc000173eb8 pc=0x4705bb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x3e fp=0xc000173f38 sp=0xc000173f00 pc=0x7395ee
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc000173f60 sp=0xc000173f38 pc=0x737dff
main.main()
	cmd/starter/main_linux.go:102 +0x5f fp=0xc000173f98 sp=0xc000173f60 pc=0x91a51f
runtime.main()
	/usr/lib64/go-1.11.1/src/runtime/proc.go:201 +0x207 fp=0xc000173fe0 sp=0xc000173f98 pc=0x430bb7
runtime.goexit()
	/usr/lib64/go-1.11.1/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000173fe8 sp=0xc000173fe0 pc=0x45c601

goroutine 5 [syscall]:
os/signal.signal_recv(0xaf7ba0)
	/usr/lib64/go-1.11.1/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/lib64/go-1.11.1/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib64/go-1.11.1/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc000242cb0)
	internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x4, 0x1b855, 0xc00000d300)
	internal/app/starter/master_linux.go:151 +0x405
main.startup()
	cmd/starter/main_linux.go:75 +0x4b8
created by main.main
	cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x1b849
rsi    0x6
rbp    0xc000173ef0
rsp    0xc000173eb0
r8     0x0
r9     0x0
r10    0x0
r11    0x206
r12    0x24
r13    0x33
r14    0xaeccdc
r15    0x0
rip    0x473c4b
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```
I have tried to troubleshoot the issue, but haven't been able to make heads or tails of this one. Have you seen this before, and can you provide guidance on how best to troubleshoot?

**Comment by valeu** [comment]
Dear Lloyd,
will it be possible for you to run the tool with an old SNP file: http://xfer.curie.fr/get/AS9Zncn7yfB/mm10_dbSNP137.ucsc.freec.txt.gz ?
Best
Valentina

**Comment by MikeWLloyd** [comment]
That was the answer. Thank you.
